document.write('<div class="module_5">')
document.write('    <div class="tricker_main2">');
document.write('            <div title="Sponsorisé par Le CCC" id="tricker4-v2">');
document.write('                <div class="link_tricker4-1">');
document.write('                <a href="https://goo.gl/Nj5DKV" target="_blank">');
document.write('               <img src="https://www.abidjan.net/images/1px-tricker.gif" width="387" height="75" border="0" /></a>');
document.write('                </div>');
document.write('                <div class="right_tricker4">');
document.write('                <div class="lg_tricker4">');
document.write('                <div class="lg_tricker4-lft"><strong>magbin</strong></div>');
document.write('                    <div class="lg_tricker0-mdl">');
document.write('<img src=https://www.abidjan.net/images/more.gif border=0 hspace=0>');
document.write('                    </div>');
document.write('                    <div class="lg_tricker0-ght">');
document.write('1616&nbsp;F/kg');
document.write('                    </div>');
document.write('                	<div class="lg_tricker4-ght">O-D</div> ');
document.write('                </div>');
document.write('                <div class="lg_tricker4">');
document.write('                <div class="lg_tricker4-lft2 lg_cBx">');
document.write('                <strong>CAFE</strong>');
document.write('            </div>');
document.write('<div class="lg_tricker0-mdl">');
document.write('<img src=https://www.abidjan.net/images/arrow_side.gif border=0 hspace=0>');
document.write('</div>  ');
document.write('<div class="lg_tricker0-ght">');
document.write('<font face=Verdana size=1><b>NC</b></font>');
document.write('</div>');
document.write('<div class="lg_tricker4-ght">O-N</div> </div>');
document.write('<div class="lg_date_tricker4"><span class="FontTextSousTitle">12/11/2019</span></div></div>');
document.write('</div>');
document.write('<div title="Sponsorisé par la MAGBIN" id="tricker5">');
document.write('<div class="link_tricker5"><a href="https://goo.gl/LGMe8n" target="_blank">');
document.write('<img src="https://www.abidjan.net/images/1px-tricker.gif" width="162" height="75" border="0" /></a></div>');
document.write('<div class="right_tricker5">');
document.write('<div class="lg_tricker5">');
document.write('<div class="txt_tricker_big_gray"><strong>PANIER DE LA MENAGERE</strong></div>');
document.write('</div>');
document.write('<div class="lg_tricker5"><div class="lg_tricker5-lft"><strong>CITRON</strong></div><div class="lg_tricker0-mdl">');
document.write('<img src="https://www.abidjan.net/images/ic_less.gif" />')
document.write('</div>  <div class="lg_tricker5-ght">300 FCFA</div>');
document.write('<div class="lg_tricker5"><div class="lg_tricker5-lft"><strong>CONCOMBRE</strong></div><div class="lg_tricker0-mdl">');
document.write('<img src="https://www.abidjan.net/images/ic_arrow_side.gif" />')
document.write('</div>  <div class="lg_tricker5-ght">300 FCFA</div> </div>');
document.write('<div class="lg_date_tricker5"><span class="FontTextSousTitle">Sem. du 10 Novembre 2019</span></div>');
document.write('<a href="https://goo.gl/vuZ12j"><div class="link_right_tricker5"></div></a>');
document.write('</div>');
document.write('</div>');
document.write('</div>');
document.write('</div>');
document.write('<div class="tricker_main">');
document.write('<div title="Sponsorisé par PETROCI" id="tricker0-2">');
document.write('<div class="link_tricker0-2"><a href="http://goo.gl/6MpstX" target="_blank">');
document.write('<img src="http://www.abidjan.net/images/1px-tricker.gif" width="91" height="75" border="0" /></a></div>');
document.write('<div class="right_tricker0-2">');
document.write('<div class="lg_tricker0"><div class="lg_tricker0-lft"><strong>BRENT</strong></div><div class="lg_tricker0-mdl">');
document.write('<img src=https://www.abidjan.net/images/more.gif border=0 hspace=0>');
document.write('</div>  <div class="lg_tricker0-ght">62.58 $</div> </div>');
document.write('<div class="lg_tricker0"><div class="lg_tricker0-lft"><strong>WTI</strong></div><div class="lg_tricker0-mdl">');
document.write('<img src=https://www.abidjan.net/images/more.gif border=0 hspace=0>');
document.write('</div>  <div class="lg_tricker0-ght">57.21 $</div> </div>');
document.write('<div class="lg_date_tricker0"><span class="FontTextSousTitle">12/11/2019</span></div>');
document.write('</div>');
document.write('</div>');
document.write('<div title="Sponsorisé par ECOBANK" id="tricker1">');
document.write('<div class="link_tricker1"><a href="https://goo.gl/rMx7B7" target="_blank">');
document.write('<img src="https://www.abidjan.net/images/1px-tricker.gif" width="100" height="75" border="0" /></a></div>');
document.write('<div class="right_tricker0">');
document.write('<div class="lg_tricker0"><div class="lg_tricker1-lft"><strong>$/CFA</strong></div><div class="lg_tricker0-mdl">');
document.write('<img src=https://www.abidjan.net/images/less.gif border=0 hspace=2>');
document.write('</div>  <div class="lg_tricker0-ght">594.403</div> </div>');
document.write('<div class="lg_tricker0"><div class="lg_tricker1-lft"><strong>£/CFA</strong></div><div class="lg_tricker0-mdl">');
document.write('<img src=https://www.abidjan.net/images/more.gif border=0 hspace=2>');
document.write('</div>  <div class="lg_tricker0-ght">764.458</div> </div>');
document.write('<div class="lg_date_tricker1"><span class="FontTextSousTitle">12/11/2019</span></div>');
document.write('</div>');
document.write('</div>');
document.write('<div title="" id="tricker2">');
document.write('<div class="link_tricker2"><a href="#" target="_blank">');
document.write('<img src="https://www.abidjan.net/images/1px-tricker.gif" width="105" height="75" border="0" /></a></div>');
document.write('<div class="right_tricker2">');
document.write('<div class="lg_tricker2"><div class="lg_tricker2-lft"><strong>CAOUTCHOUC</strong></div><div class="lg_tricker0-mdl">');
document.write('<img src=https://www.abidjan.net/images/more.gif border=0 hspace=2>');
document.write('</div>  <div class="lg_tricker0-ght">150.3 USCT/kg</div> </div>');
document.write('<div class="lg_tricker2"><div class="lg_tricker2-lft"><strong>SUCRE</strong></div><div class="lg_tricker0-mdl">');
document.write('<img src=https://www.abidjan.net/images/more.gif border=0 hspace=2>');
document.write('</div>  <div class="lg_tricker0-ght">269.64 $/tonne</div> </div>');
document.write('<div class="lg_tricker2"><div class="lg_tricker2-lft"><strong>PALME</strong></div><div class="lg_tricker0-mdl">');
document.write('<img src=https://www.abidjan.net/images/more.gif border=0 hspace=2>');
document.write('</div>  <div class="lg_tricker0-ght">517.5 $/tonne</div> </div>');
document.write('<div class="lg_date_tricker2"><span class="FontTextSousTitle">2/5/2019</span></div>');
document.write('</div>');
document.write('</div>');
document.write('<div title="Sponsorisé par la BRVM" id="tricker3">');
document.write('<div class="link_tricker3"><a href="https://goo.gl/pqA6Ha" target="_blank">');
document.write('<img src="https://www.abidjan.net/images/1px-tricker.gif" width="108" height="75" border="0" /></a></div>');
document.write('<div class="right_tricker3">');
document.write('<div class="lg_tricker3"><div class="lg_tricker3-lft"><strong>BRVM 10</strong></div>');
document.write('<div class="lg_tricker3-ght">134.02</div><div class="lg_tricker0-mdl">');
document.write('<img src=https://www.abidjan.net/images/more.gif border=0>');
document.write('</div>');
document.write('<div class="lg_tricker0-ght"><font color="#669900"> + 0.53</font></div>');
document.write('</div>');
document.write('<div class="lg_tricker3"><div class="lg_tricker3-lft"><strong>BRVM C</strong></div>');
document.write('<div class="lg_tricker3-ght">141.32</div><div class="lg_tricker0-mdl">');
document.write('<img src=https://www.abidjan.net/images/more.gif border=0>');
document.write('</div>');
document.write('<div class="lg_tricker0-ght"><font color="#669900"> + 0.42</font></div>');
document.write('</div>');
document.write('<div class="lg_date_tricker3"><span class="FontTextSousTitle">Abidjan le 12/11/2019 | <a href="https://business.abidjan.net/bourse/">Le BOC</a></span></div>');
document.write('<a href="https://goo.gl/u6DE27"><div class="link_right_tricker3"></div></a>');
document.write('</div>');
document.write('</div>');
document.write('</div>');
document.write('<div class="tricker_main3">');
document.write('    <div id="tricker7-contener" style="margin: 0 auto !important; float: none !important; width: 500px;"><div title="Sponsorisé par Le CCA" id="tricker7">');
document.write('                <div class="link_tricker7">');
document.write('                <a href="https://goo.gl/XFi73J" target="_blank">');
document.write('               <img src="https://www.abidjan.net/images/1px-tricker.gif" width="387" height="75" border="0" /></a>');
document.write('                </div>');
document.write('                <div class="right_tricker7">');
document.write('                <div class="lg_tricker7">');
document.write('                <div class="lg_tricker7-lft2"><strong>COTON</strong></div>');
document.write('                   <div class="lg_tricker0-mdl">');
document.write('<img src=https://www.abidjan.net/images/less.gif border=0>');
document.write('                   </div>');
document.write('                    <div class="lg_tricker0-ght">');
document.write('844.05&nbsp;F/Kg');
document.write('</div>');
document.write('                </div>');
document.write('                <div class="lg_tricker7">');
document.write('                <div class="lg_tricker7-lft2">');
document.write('                <strong>ANACARDE</strong>');
document.write('            </div>');
document.write('<div class="lg_tricker0-mdl">');
document.write('<img src="https://www.abidjan.net/images/arrow_side.gif" width="5" height="5" border="0" hspace="0">');
document.write('</div>  ');
document.write('<div class="lg_tricker0-ght">');
document.write('Bientôt');
document.write('</div></div>');
document.write('<div class="lg_date_tricker7"><span class="FontTextSousTitle">11/11/2019</span></div></div>');
document.write('</div></div>');
document.write('</div>');
document.write('</div>');